### ISSUE TITLE
Placeholder names with uppercase letters

### ISSUE THREAD

**Issue by burntcustard** [wearelighthouse/scss#22]
```
placeholder-name-format:
    - 1
    - convention: hyphenatedbem
```
Doesn't allow for uppercase characters, so for example:
```
%u-translateX--50pc;
```
Comes up with a warning!

I'd like to allow these, because some CSS values that we're setting with our placeholders traditionally get written with uppercase letters, like  `transform: translateX()`

So I think we should
```
placeholder-name-format:
    - 1
    - convention: ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)*(?:\\[.+\\])?$
    - convention-explanation: 'hypenatedbem uppercase & multiple modifiers allowed'
```
